apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-values
  namespace: nextcloud
stringData:
  values.yaml: |
    nextcloud:
      host: nextcloud.example.com
      username: admin
      password: secret
